## Lire un fichier

In [1]:
import pandas as pd
food_info = pd.read_csv("food_info.csv")
print (type(food_info))

<class 'pandas.core.frame.DataFrame'>

In [2]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0

## Selectionner un ou plusieurs elements

### Selectionner une ligne

In [3]:
row_100 = food_info.loc[99]
print(row_100)

NDB_No                                  1111
Shrt_Desc          MILK SHAKES THICK VANILLA
Water_(g)                              74.45
Energ_Kcal                               112
Protein_(g)                             3.86
Lipid_Tot_(g)                           3.03
Ash_(g)                                 0.91
Carbohydrt_(g)                         17.75
Fiber_TD_(g)                             0.0
Sugar_Tot_(g)                          17.75
Calcium_(mg)                           146.0
Iron_(mg)                                0.1
Magnesium_(mg)                          12.0
Phosphorus_(mg)                        115.0
Potassium_(mg)                         183.0
Sodium_(mg)                             95.0
Zinc_(mg)                               0.39
Copper_(mg)                            0.051
Manganese_(mg)                         0.014
Selenium_(mcg)                           2.3
Vit_C_(mg)                               0.0
Thiamin_(mg)                            0.03
Riboflavin_(mg)                        0.195
Niacin_(mg)                            0.146
Vit_B6_(mg)                            0.042
Vit_B12_(mcg)                           0.52
Vit_A_IU                                91.0
Vit_A_RAE                               25.0
Vit_E_(mg)                              0.05
Vit_D_mcg                                1.2
Vit_D_IU                                48.0
Vit_K_(mcg)                              0.2
FA_Sat_(g)                             1.886
FA_Mono_(g)                            0.875
FA_Poly_(g)                            0.113
Cholestrl_(mg)                          12.0
Name: 99, dtype: object

In [4]:
last_rows = food_info.loc[len(food_info)-5:len(food_info)]
last_rows

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
8613,83110,MACKEREL SALTED,43.00,305,18.50,25.10,13.40,0.00,0.0,0.0,...,157.0,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0
8614,90240,SCALLOP (BAY&SEA) CKD STMD,70.25,111,20.54,0.84,2.97,5.41,0.0,0.0,...,5.0,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0
8615,90480,SYRUP CANE,26.00,269,0.00,0.00,0.86,73.14,0.0,73.2,...,0.0,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0
8616,90560,SNAIL RAW,79.20,90,16.10,1.40,1.30,2.00,0.0,0.0,...,100.0,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0
8617,93600,TURTLE GREEN RAW,78.50,89,19.80,0.50,1.20,0.00,0.0,0.0,...,100.0,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0

### Selectionner une colonne

In [5]:
protein = food_info["Protein_(g)"]
cholesterol = food_info ["Cholestrl_(mg)"]
print (protein)
print (cholesterol)

0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
        ...
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64
0       215.0
1       219.0
2       256.0
3        75.0
4        94.0
        ...
8613     95.0
8614     41.0
8615      0.0
8616     50.0
8617     50.0
Name: Cholestrl_(mg), Length: 8618, dtype: float64

In [6]:
selenium_thiamin = food_info [["Shrt_Desc","Selenium_(mcg)","Thiamin_(mg)"]]
print(selenium_thiamin)

                       Shrt_Desc  Selenium_(mcg)  Thiamin_(mg)
0               BUTTER WITH SALT             1.0         0.005
1       BUTTER WHIPPED WITH SALT             1.0         0.005
2           BUTTER OIL ANHYDROUS             0.0         0.001
3                    CHEESE BLUE            14.5         0.029
4                   CHEESE BRICK            14.5         0.014
...                          ...             ...           ...
8613             MACKEREL SALTED            73.4         0.020
8614  SCALLOP (BAY&SEA) CKD STMD            21.7         0.012
8615                  SYRUP CANE             0.7         0.130
8616                   SNAIL RAW            27.4         0.010
8617            TURTLE GREEN RAW            16.8         0.120

[8618 rows x 3 columns]

# Cas pratique

SÃ©lectionner et afficher seulement les colonnes qui utilisent comme unitÃ© de mesure les grammes (c'est Ã  dire qui se terminent par "(g)"). Pour cela:

. Utiliser l'attribut columns pour retourner le nom des colonnes du dataframe food_info et convertir en liste utilisant la mÃ©thode tolist()

. CrÃ©er une nouvelle liste qu'on nommera gram__columns, contenant seulement les colonnes se terminant par "(g)". Indice: la mÃ©thode endswith() retourne True si l'objet sur lequel on l'applique se termine par l'Ã©lÃ©ment entre parenthÃ¨ses. ex: total_(g).endswith("(g)") retourne True. Une boucle for est fortement conseillÃ© pour parcourir tous les noms de colonne.

. SÃ©lectionner les colonnes de gram_columns pour le dataframe food_info et assigner le dataframe rÃ©sultat Ã  la variable gram_df

. Afficher les 3 premiÃ¨res valeurs de ce dataframe gram_df

In [7]:
col = food_info.columns
col = col.tolist()
gram_columns =[]
for element in col:
    if element.endswith("(g)"):
        gram_columns.append(element)
gram_df = food_info[gram_columns]
print (gram_df.head(3))

   Water_(g)  Protein_(g)  Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  \
0      15.87         0.85          81.11     2.11            0.06
1      15.87         0.85          81.11     2.11            0.06
2       0.24         0.28          99.48     0.00            0.00

   Fiber_TD_(g)  Sugar_Tot_(g)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)
0           0.0           0.06      51.368       21.021        3.043
1           0.0           0.06      50.489       23.426        3.012
2           0.0           0.00      61.924       28.732        3.694